In [64]:
#First, lets import all the libraries to be used on this notebook
import pandas as pd
import numpy as np
import geocoder
print('Libraries Imported!')

Libraries Imported!

In [65]:

#Read postcodes into a pandas dataframe
df_neighborhoods = pd.read_csv('Toronto.csv',index_col=[0])
df_neighborhoods.head()

  Postal Code      Borough                            Neighborhood
0         M1B  Scarborough                          Malvern, Rouge
1         M1C  Scarborough  Rouge Hill, Port Union, Highland Creek
2         M1E  Scarborough       Guildwood, Morningside, West Hill
3         M1G  Scarborough                                  Woburn
4         M1H  Scarborough                               Cedarbrae

In [66]:
#Create function to get coordinates of a specific postcode. Added "Max Iterations" parameter to limit the number of
#iterations for the API call, and a "Debug" parameter to show the progress of the for loop

def get_coordinates_toronto(postal_code, max_iterations, debug):
    lat_lng_coords = None
    success=False
    for i in range(max_iterations):
        g = geocoder.google('{}, Toronto, Ontario'.format(postal_code))
        lat_lng_coords = g.latlng
        if debug:
            print('Attempt #: {}, Coordinates: {}'.format(i+1, lat_lng_coords))
        if lat_lng_coords is not None:
            success=True
            break
    if success:
        latitude = lat_lng_coords[0]
        longitude = lat_lng_coords[1]
        return latitude, longitude
    else:
        return 'Failed to get coordinates'

In [67]:
#Test the function (10 iterations, print the progress)
get_coordinates_toronto('M1C',10,True)

Attempt #: 1, Coordinates: None
Attempt #: 2, Coordinates: None
Attempt #: 3, Coordinates: None
Attempt #: 4, Coordinates: None
Attempt #: 5, Coordinates: None
Attempt #: 6, Coordinates: None
Attempt #: 7, Coordinates: None
Attempt #: 8, Coordinates: None
Attempt #: 9, Coordinates: None
Attempt #: 10, Coordinates: None

'Failed to get coordinates'

In [68]:
#Read CSV file from link and load into dataframe
url_csv = 'http://cocl.us/Geospatial_data'
df_coordinates = pd.read_csv(url_csv)
df_coordinates.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [69]:
# Make sure both dataframes have the same 
df_coordinates.rename(columns={'Postal Code': 'Postal Code'}, inplace=True)
df_neighborhoods.rename(columns={'Postal Code': 'Postal Code'}, inplace=True)

In [71]:
# Merge both datasets
df_neighborhoods_coordinates = pd.merge(df_neighborhoods, df_coordinates, on='Postal Code')
df_neighborhoods_coordinates.head()

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476

In [76]:
# create a new test dataframe
column_names = ["Postal Code", "Borough", "Neighborhood", "Latitude", "Longitude"]
test_df = pd.DataFrame(columns=column_names)

test_list = ["M5G", "M2H", "M4B", "M1J", "M4G", "M4M", "M1R", "M9V", "M9L", "M5V", "M1B", "M5A"]

for postcode in test_list:
    test_df = test_df.append(df_neighborhoods_coordinates[df_neighborhoods_coordinates["Postal Code"]==postcode], ignore_index=True)
    
test_df

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M5G,Downtown Toronto,Central Bay Street,43.657952,-79.387383
1,M2H,North York,Hillcrest Village,43.803762,-79.363452
2,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
3,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
4,M4G,East York,Leaside,43.709060,-79.363452
5,M4M,East Toronto,Studio District,43.659526,-79.340923
6,M1R,Scarborough,"Wexford, Maryvale",43.750072,-79.295849
7,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
8,M9L,North York,Humber Summit,43.756303,-79.565963
9,M5V,Downtown Toronto,"CN Tower, King and Spadina, Railway Lands, Har...",43.628947,-79.394420
10,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
11,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636

In [ ]:
#Export to .CSV
df_neighborhoods_coordinates.to_csv('Toronto2.csv')